'use strict';
const $=selector=>document.querySelector(selector);
const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const session=$('meta[name="auryqen-session"]').content;
let current='home',currentChat=null,appState=null,chatMessages=[],busy=false;
const toast=(message,bad=false)=>{const n=$('#notice');n.textContent=message;n.className=bad?'bad':'';n.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>n.style.display='none',4500)};
async function api(path,body){const response=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:{'X-Auryqen-Session':session,...(body===undefined?{}:{'Content-Type':'application/json'})},...(body===undefined?{}:{body:JSON.stringify(body)})});const value=await response.json();if(!response.ok)throw Error(value.error||'Request failed');return value}
const taskStatus=t=>'<span class="muted">'+escapeHTML(t.status)+'</span>';
async function refresh(){appState=await api('state');$('#model-status').textContent=appState.model_connected?'MODEL CONNECTED':'MODEL UNCONFIGURED';$('#model-status').classList.toggle('ok',appState.model_connected);$('#pending').textContent=appState.approvals.length?'('+appState.approvals.length+')':'';render()}
function hero(title,desc){return '<div class="hero"><small>AURYQEN / LIVE CORE</small><h1>'+escapeHTML(title)+'</h1><p>'+escapeHTML(desc)+'</p></div>'}
function recent(){return '<div class="listing">'+(appState.tasks.map(t=>'<div class="item"><b>'+escapeHTML(t.capability)+' · '+taskStatus(t)+'</b><small>'+escapeHTML(t.id)+' / '+escapeHTML(t.caller)+'</small><pre>'+escapeHTML(JSON.stringify(t.result??t.error??t.input,null,2))+'</pre></div>').join('')||'<p>No tasks yet.</p>')+'</div>'}
function home(){return hero('Capabilities that perform actual work.','This interface and the MCP adapter call the same SQLite-backed execution core. Operations are real; completed tasks have actual results and recorded events.')+'<div class="cards">'+[['Capabilities',appState.capabilities.length],['Tasks',appState.tasks.length],['Events',appState.events.length],['Approvals',appState.approvals.length]].map(([title,num])=>'<div class="card"><small>'+title+'</small><b>'+num+'</b></div>').join('')+'</div><div class="grid"><div class="panel"><h2>Submit a capability</h2><div class="form"><label for="cap">Capability</label><select id="cap">'+appState.capabilities.map(c=>'<option value="'+escapeHTML(c.id)+'">'+escapeHTML(c.name)+' — '+escapeHTML(c.id)+'</option>').join('')+'</select><label for="payload">Input · JSON</label><textarea id="payload">{}</textarea><button class="primary" data-action="invoke">Execute through core</button></div><div class="warning">directory.inspect accepts {"path":"."}, relative to the explicitly configured allowed root. memory.write requests owner approval.</div></div><div class="panel"><h2>Recent tasks</h2>'+recent()+'</div></div>'}
function talk(){return hero('Talk to Auryqen.','Messages, actual model replies, and real capability results are persisted. No model is connected unless the indicator says otherwise.')+'<div class="grid"><div class="panel"><div class="row"><select id="conversation" aria-label="Conversation"><option value="">Select conversation</option>'+appState.conversations.map(c=>'<option value="'+escapeHTML(c.id)+'" '+(c.id===currentChat?'selected':'')+'>'+escapeHTML(c.title)+'</option>').join('')+'</select><button data-action="new-chat">New</button></div><div class="chat" id="chat">'+(chatMessages.map(m=>'<div class="bubble '+escapeHTML(m.role)+'"><small>'+escapeHTML(m.role)+' · '+escapeHTML(m.created)+'</small><br>'+escapeHTML(m.content)+'</div>').join('')||'<p>No messages yet.</p>')+'</div><div class="form" style="margin-top:12px"><label for="message">Message</label><textarea id="message" placeholder="Ask the connected AI, or save a message until a provider is configured."></textarea><button class="primary" data-action="send" '+(busy?'disabled':'')+'>Send message</button></div></div><div class="panel"><h2>Shared execution path</h2><p>A connected model proposes a capability call. The core independently validates input, verifies permission, creates the task, executes or requests approval, and records events. ChatGPT via MCP uses the same path.</p><div class="warning">'+(appState.model_connected?'Model adapter is configured. Replies and usage depend on the connected provider.':'No model is configured. Sending a message saves it, but does not invent an AI reply. You can use the direct capability controls now.')+'</div><h2>Recent task evidence</h2>'+recent()+'</div></div>'}
function capabilities(){return hero('The registry is shared.','Each caller invokes the same capability identifier and passes through the same authorization boundary.')+'<div class="listing">'+appState.capabilities.map(c=>'<div class="item"><b>'+escapeHTML(c.name)+' · '+escapeHTML(c.id)+'</b><small>'+escapeHTML(c.description)+' / '+escapeHTML(c.kind)+' / '+(c.granted?'Owner grant enabled':'Not granted')+'</small></div>').join('')+'</div>'}
function approvals(){return hero('Owner approval required.','Pending write actions cannot execute until you explicitly approve them here.')+'<div class="listing">'+(appState.approvals.map(a=>'<div class="item"><b>'+escapeHTML(a.id)+'</b><small>Task '+escapeHTML(a.task_id)+' · '+escapeHTML(a.status)+'</small><div class="row" style="margin-top:10px"><button class="primary" data-action="approve" data-id="'+escapeHTML(a.id)+'">Approve</button><button data-action="deny" data-id="'+escapeHTML(a.id)+'">Deny</button></div></div>').join('')||'<p>No pending approvals.</p>')+'</div>'}
function events(){return hero('Actual execution events.','Recorded in SQLite with task correlation, not generated animation.')+'<div class="listing">'+appState.events.slice().reverse().map(e=>'<div class="item"><b>#'+e.seq+' '+escapeHTML(e.type)+'</b><small>'+escapeHTML(e.task_id||'platform')+' · '+escapeHTML(e.created)+'</small><pre>'+escapeHTML(JSON.stringify(e.payload,null,2))+'</pre></div>').join('')+'</div>'}
function render(){if(!appState)return;document.querySelectorAll('nav [data-view]').forEach(n=>n.classList.toggle('active',n.dataset.view===current));$('#crumb').textContent=current.toUpperCase();$('#content').innerHTML=({home,talk,capabilities,approvals,events}[current]||home)()}
async function openChat(id){currentChat=id;chatMessages=id?await api('messages/'+encodeURIComponent(id)):[];render()}
function handle(action,id){return (async()=>{if(action==='invoke'){const capability=$('#cap').value,input=JSON.parse($('#payload').value);const t=await api('tasks',{capability,input});toast(t.status==='pending_approval'?'Task pending your approval':t.status==='completed'?'Task completed: '+t.id:t.status+': '+(t.error||t.id),t.status==='failed'||t.status==='rejected');await refresh()}
else if(action==='new-chat'){const title=prompt('Conversation title','New conversation');if(title===null)return;const r=await api('conversations',{title});await refresh();await openChat(r.id)}
else if(action==='send'){if(busy)return;if(!currentChat){toast('Create or select a conversation first',true);return}const message=$('#message').value.trim();if(!message)return;busy=true;try{const r=await api('chat',{conversation_id:currentChat,message});await refresh();await openChat(currentChat);toast(r.connected?'Assistant responded':r.message)}finally{busy=false;render()}}
else if(action==='approve'||action==='deny'){const allow=action==='approve';const task=await api('approvals/resolve',{id,allow});toast('Task '+task.status);await refresh()}})().catch(e=>{busy=false;toast(e.message,true);render()})}
document.querySelectorAll('nav [data-view]').forEach(btn=>btn.addEventListener('click',()=>{current=btn.dataset.view;render()}));$('#content').addEventListener('click',e=>{const btn=e.target.closest('[data-action]');if(btn)handle(btn.dataset.action,btn.dataset.id)});$('#content').addEventListener('change',e=>{if(e.target.id==='conversation')openChat(e.target.value).catch(x=>toast(x.message,true))});
refresh().catch(e=>{$('#content').textContent='Cannot access the local runtime: '+e.message});